---
- name: Install consul
  shell: "{{ consul_installation_path }} --version {{ consul_installation_version }} --path {{ consul_dir_path }} --user {{ consul_user }} --ca-file-path {{ consul_installation_ca_file_path }} --cert-file-path {{ consul_installation_cert_file_path }} --key-file-path {{ consul_installation_key_file_path }}"
  args:
    executable: /bin/bash
  become: yes