---
- name: Install consul
  shell: "{{ consul_installation_path }} --version {{ consul_installation_version }} --path {{ consul_dir_path }} --user {{ consul_user }} --ca-file-path {{ consul_installation_ca_file_path }} --cert-file-path {{ consul_installation_cert_file_path }} --key-file-path {{ consul_installation_key_file_path }}"
  args:
    executable: /bin/bash
  become: yes

- name: Create consul scripts directory
  file:
    dest: "{{ consul_script_dir }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: 0755

- name: Install server startup script
  template:
    src: startup-script-server.sh.j2
    dest: "{{ consul_script_dir }}/server-startup.sh"
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: "a+x"

- name: Install server startup script
  template:
    src: startup-script-client.sh.j2
    dest: "{{ consul_script_dir }}/client-startup.sh"
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: "a+x"

- name: Install shutdown script
  template:
    src: shutdown-script.sh.j2
    dest: "{{ consul_script_dir }}/shutdown.sh"
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: "a+x"

- name: Install acl bootstrap script
  template:
    src: bootstrap-acl.sh.j2
    dest: "{{ consul_script_dir }}/bootstrap-acl.sh"
    owner: "{{ consul_user }}"
    group: "{{ consul_user }}"
    mode: "a+x"