---
- name: Install consul
  shell: "{{ consul_installation_path }} --version {{ consul_installation_version }} --path {{ consul_dir_path }} --user {{ consul_user }} --ca-file-path {{ consul_installation_ca_file_path }} --cert-file-path {{ consul_installation_cert_file_path }} --key-file-path {{ consul_installation_key_file_path }}"
  args:
    executable: /bin/bash
  become: yes
- name: Install server startup script
  vars:
    - consul_mode
  template:
    src: startup-script-server.sh.j2
    dest: /opt/consul/scripts/startup.sh
    owner: consul
    group: consul
    mode: "a+x"
  when:
    consul_mode | "server"

- name: Install client startup script
  vars:
    - consul_mode
  template:
    src: startup-script-client.sh.j2
    dest: /opt/consul/scripts/startup.sh
    owner: consul
    group: consul
    mode: "a+x"
  when:
    consul_mode | "client"

- name: Install shutdown script
  template:
    src: shutdown-script.sh.j2
    dest: /opt/consul/scripts/shutdown.sh
    owner: consul
    group: consul
    mode: "a+x"
