---
# Update OS and install dnsmasq
- name: Install dnsmasq
  shell: "{{ dnsmasq_installation_path }} --consul-domain {{ consul_domain }} --consul-ip {{ consul_ip }} --consul-dns-port {{ consul_dns_port }}"
  args:
    executable: /bin/bash
  become: yes